### ISSUE TITLE
FE와의 통신 세팅

### ISSUE THREAD

**Issue by Yeonsu-Sim** [jnu-sf-engineering/backend#22]
## ✏️ Description
FE와의 통신 세팅을 위한 Docker hub에 이미지 업로드

## 🎟️ Tickets
- [x] SpringBoot Dockerfile 작성
- [x] docker-compose-dev.yaml 파일에 SpringBoot Dockerfile 반영
- [x] 로컬 Docker hub에 push 진행
- [x] FE 로컬에 Docker hub pull 진행
