### ISSUE TITLE
setting: 프로젝트 진행을 위한 초기 세팅

### ISSUE THREAD

**Issue by Kyeong6** [jnu-sf-engineering/backend#3]
## ✏️ Description

프로젝트 진행을 위한 세팅 진행
## 🎟️ Tickets

- [x] Discord Webhook을 이용한 Github 연동
- [x] Github Repository Wiki에 Branch Strategy, Commit convention, Projects 작성 및 설정
- [x] Project Architecture 설계
- [x] ERD 설계
- [x] Issues, PR 템플릿 작성
- [x] Spring Boot Project 생성
